### ISSUE TITLE
SSH Key Addition

### ISSUE THREAD

**Issue by adamrpostjr** [robsonde/digitalocean_builder#2] opened 2021-11-02 16:32 UTC
When adding more than one ssh key they get placed on the same line of the authorized_key file causing the second key not to work

**Comment by robsonde** [comment] 2021-11-07 04:05
Root cause was bug in https://github.com/robsonde/digital-ocean-synchronize-AUR
Now fixed.
Thanks for reporting.

**Closed as completed by robsonde** 2021-11-07 04:05 UTC
